### ISSUE TITLE
Incorrect QR code data

### ISSUE THREAD

**Issue by thebiltheory** [expo/expo-preview-action#6]
### Description of the bug

How would you shortly summarize the issue?
![IMG_1800](https://user-images.githubusercontent.com/2975322/130109292-9050eba2-0ffe-4d3c-99c7-932093e5e750.PNG)

### To Reproduce
What steps did you perform which led to this issue?

```yaml
name: Expo Review and Preview
on: [pull_request]
jobs:
  preview:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set up Expo
        uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Publish to expo and create a QR code
        uses: expo/expo-preview-action@v1
        with:
          channel: pr-${{ github.event.number }}
        id: preview

      - name: Comment deployment link
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_GH_TOKEN }}
        with:
          msg: >
            Awesome! Your Pull Request Preview App is ready for testing, you can [see it here](https://expo.io/@garaji/garaji-marketplace?release-channel=pr-${{ github.event.number }}).
            <a href="${{ steps.publish.outputs.EXPO_QR_CODE_URL }}"><img src="${{ steps.preview.outputs.EXPO_QR_CODE_URL }}" height="512px" width="512px"></a>
            <br><br>
            ${{ steps.publish.outputs.EXPO_NEW_BUILD_IS_REQUIRED_MESSAGE }}
```

#### Expected behavior

What did you expect to have happened?
Open the Expo Go client

#### Actual behavior

What did it actually result in?
Incorrect data in the QR code

### Additional context

Can you further explain the issue? E.g., information about version/environment or screenshots.
